### ISSUE TITLE
decrypt_1函数貌似存在bug

### ISSUE THREAD

**Issue by 592767809** [nilaoda/qsv_unpacker#2]
解密后的几个字节是乱码，应该是解密长度不正确

修改为

def decrypt_1(buffer):
    key = [0x62, 0x67, 0x70, 0x79]
    for i in range(len(buffer) // 4 * 4):
        j = ~i & 0x3
        buffer[i] ^= key[j]
    return bytes(buffer)

解密后去除前8字节可以直接json序列化

**Comment by nilaoda** [comment]
确实是这样，感谢指正!
